# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class RecodeShoupiao(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(30)
        self.base_url = "https://guanplus-app-accountingfirm-web-stage.cn-north-1.eb.amazonaws.com.cn/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_recode_shoupiao(self):
        driver = self.driver
        driver.get(self.base_url + "/login")
        driver.find_element_by_id("recipient-name").clear()
        driver.find_element_by_id("recipient-name").send_keys("Qq123456")
        driver.find_element_by_id("usernameInput").clear()
        driver.find_element_by_id("usernameInput").send_keys("13683139989")
        driver.find_element_by_id("passwordInput").clear()
        driver.find_element_by_id("passwordInput").send_keys("Qq123456")
        driver.find_element_by_id("loginButton").click()
        driver.find_element_by_link_text(u"有序0726回归（勿动）").click()
        driver.find_element_by_id("transactionSideMenu").click()
        driver.find_element_by_xpath("//ul[@id='side-menu-child']/div/ul/ul[2]/li[3]/a/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000001")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_css_selector("div.option-text").click()
        driver.find_element_by_css_selector("button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("100")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"其他－福利费－管理，借－56020104福利费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000002")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[2]/div[2]").click()
        driver.find_element_by_css_selector("button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("200")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"其他－招待费－管理，借－56020201招待费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000003")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[2]/div[2]/div").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("300")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"内部代表－办公费－管理，借－56020202办公费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000004")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[3]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[2]/div[2]/div").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[3]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("500")
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("400")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"其他－快递费－管理，借－56020203快递费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_css_selector("div.col-sm-6").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000005")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[2]/div[2]").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[4]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("500")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"内部代表－通讯费－管理，借－56020204通讯费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000006")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[3]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[2]/div[2]/div").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[5]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("600")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"其他－维修费－管理，借－56020205维修费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000007")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[2]/div[2]").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[6]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("700")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"内部代表－财产保险费－管理，借－56020206财产保险费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[3]/div/a/div[2]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000008")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[3]/div[2]").click()
        driver.find_element_by_css_selector("li.option-active > div.parent-options").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[7]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("800")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"其他－设备租赁费－管理，借－56020207设备租赁费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000009")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[3]/div[2]").click()
        driver.find_element_by_css_selector("li.option-active > div.parent-options").click()
        driver.find_element_by_xpath("//div[@id='wrapper']/browser-alert/div/div/div").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.active > a.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[8]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("900")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"内部代表－银行费用－管理，借－560302手续费用，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[3]/div/a/div[2]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000010")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[3]/div[2]").click()
        driver.find_element_by_css_selector("button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.active > a.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("1000")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"其他－差旅费－管理，借－5602030差旅费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000011")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[3]/div[2]/div").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[3]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("1100")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"内部代表－交通费－管理，借－56020302交通费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000012")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[3]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[3]/div[2]/div").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[3]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[4]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("1200")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"其他－汽油费－管理，借－56020303汽油费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000013")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[3]/div[2]").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/i").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[4]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("1300")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"内部代表－路桥费－管理，借－56020304路桥费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[3]/div/a/div[2]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000013")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[3]/div[2]/div").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[4]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[3]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("13")
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000014")
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("1400")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"其他－汽车维修费－管理，借－56020305汽车维修费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span/i").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000015")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[3]/div[2]/div").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[4]/div[2]/div").click()
        driver.find_element_by_css_selector("li.option-active > div.parent-options > div.option-text").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[4]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[4]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("1500")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"内部代表－汽车保险费－管理，借－56020306汽车保险费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000016")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[4]/div[2]").click()
        driver.find_element_by_css_selector("li.option-active > div.parent-options > div.option-text").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[5]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("16000")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"其他－物流费－管理，借－56020307物流费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000017")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[3]/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[4]/div[2]").click()
        driver.find_element_by_css_selector("button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[5]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("1700")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"内部代表－房租费－管理，借－56020401房租费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000018")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[4]/div[2]").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[5]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.active > a.dropdown-item").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("1800")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"其他－物业费－管理，借－56020402物业费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000019")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[4]/div[2]/div").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[5]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[4]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("1900")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"内部代表－水费－管理，借－56020403水费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000020")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[4]/div[2]").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[5]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[5]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("2000")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"其他－电费－管理，借－56020404电费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000021")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[4]/div[2]").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[6]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("2100")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"内部代表－仓储费－管理，借－56020405仓储费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000022")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[4]/div[2]").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[7]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("2200")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"其他－装修费－管理，借－56020406装修费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000023")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[5]/div[2]").click()
        driver.find_element_by_css_selector("button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[7]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("2300")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"内部代表－广告费－管理，借－56020501广告费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000024")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[5]/div[2]").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li[7]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button[3]").click()
        driver.find_element_by_id("confirmButton").click()
        driver.find_element_by_xpath("//main[@id='body']/input-invoice/div/div[3]/div/div/table/tbody/tr/td[10]/button[2]").click()
        driver.find_element_by_id("confirmButton").click()
        driver.find_element_by_xpath("//main[@id='body']/input-invoice/div/div[3]/div/div/table/tbody/tr/td[10]/button[2]").click()
        driver.find_element_by_id("confirmButton").click()
        driver.find_element_by_xpath("//main[@id='body']/input-invoice/div/div[3]/div/div/table/tbody/tr/td[10]/button").click()
        driver.find_element_by_id("newItem").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[2]/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[2]/td/ng-select/div/div[2]/ul/li[4]/div[2]").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_id("newItem").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[3]/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[3]/td/ng-select/div/div[2]/ul/li[5]/div[2]").click()
        driver.find_element_by_css_selector("button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[2]/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[2]/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[3]/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[3]/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[2]/td[3]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[2]/td[3]/ng-select/div/ul/li[7]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[3]/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[3]/td[3]/ng-select/div/ul/li[7]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[2]/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[2]/td[4]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[3]/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/edit-input-invoice/div/div[2]/ul/table/tbody/tr[3]/td[4]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("(//input[@type='number'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='number'])[2]").send_keys("2200")
        driver.find_element_by_xpath("(//input[@type='number'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='number'])[3]").send_keys("2300")
        driver.find_element_by_xpath("(//input[@type='text'])[4]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[4]").send_keys(u"其他－装修费－管理，借－56020406装修费，贷－22410101临时借入款")
        driver.find_element_by_xpath("(//input[@type='text'])[5]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[5]").send_keys(u"内部代表－广告费－管理，借－56020501广告费，贷－22410101临时借入款")
        driver.find_element_by_css_selector("button.btn.btn-primary").click()
        driver.find_element_by_xpath("//main[@id='body']/input-invoice/div/div[2]/div/ol/li[3]/button[3]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[2]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000027")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[5]/div[2]").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("2400")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"其他－宣传费－管理，借－56020502宣传费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_css_selector("input.form-control.ui-select-search").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div/div/label[3]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").click()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[2]").send_keys("00000028")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td/ng-select/div/div[2]/ul/li[5]/div[2]").click()
        driver.find_element_by_css_selector("div.ui-select-choices-row.option-active > div.children-options > button.dropdown-item").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/div[2]/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[2]/ng-select/div/ul/li[2]/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[3]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/div[2]/span/span").click()
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/table/tbody/tr/td[4]/ng-select/div/ul/li/div/a/div[2]").click()
        driver.find_element_by_xpath("//input[@type='number']").clear()
        driver.find_element_by_xpath("//input[@type='number']").send_keys("2500")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys(u"内部代表－研发费－管理，借－56020503研发费，贷－22410101临时借入款")
        driver.find_element_by_xpath("//main[@id='body']/tab/new-input-invoice/div/div[2]/ul/div[3]/div/span/button[2]").click()
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException as e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
